Git workflow for running jest test (Review comments)
Signed-off-by: Zoltan Magyari <codesage.control175@passmail.net>

diff --git a/.github/workflows/branch-push.yaml b/.github/workflows/branch-push.yaml
--- a/.github/workflows/branch-push.yaml
+++ b/.github/workflows/branch-push.yaml
@@ -32,8 +32,6 @@ jobs:
 
       # Step 4: Run Jest tests
       - name: Run Jest tests
-        # TODO: Adapt to run coverage on changed files only.
-        # run: npm test -- --coverage # $(git diff --name-only origin/main...HEAD | grep '\.[jt]sx\?$' | grep -v '\ .test\.')
         run: npm test -- --coverage
         env:
           CI: true  # Ensures Jest runs in CI mode
@@ -47,14 +45,33 @@ jobs:
           retention-days: 7
 
       # Step 6: Fail the job if there are uncovered files (js, ts, jsx, tsx)
-      # TODO: It needs to be implemented.
+      - name: Check uncovered files
+        run: |
+          # Step 1: Get the list of changed JS, TS, JSX and TSX files in the src directory
+          CHANGED_FILES=$(git diff --name-only origin/main...HEAD | grep '^src/.*\.[jt]sx\?$' | grep -v '\ .test\.')
+          
+          # Initialize an empty array to hold files without tests
+          MISSING_TEST_FILES=()
+          
+          # Step 2: Loop through each changed file and check if it has a corresponding test file
+          for FILE in $CHANGED_FILES; do
+            # Extract the file path and replace "src/" with "tests/" and add ".test" postfix
+            TEST_FILE=$(echo "$FILE" | sed 's|^src/|tests/|' | sed 's|\.[jt]sx\?$|.test&|')
 
-      # Step 7: Fail the job if the test coverage is below a threshold (optional)
-      # TODO: This should be removed because it is solved within 'jest.config.js' by setting the 'coverageThreshold'.
-      # - name: Check coverage threshold
-      #  run: |
-      #    COVERAGE=$(grep -o '"total": {.*}' coverage/coverage-summary.json | grep -o '"lines":{.*}$' | grep -o '"pct":[0-9]*' | grep -m 1 '"pct":[0-9]*' | grep -o '[0-9]*')
-      #    if [ "$COVERAGE" -lt 90 ]; then
-      #      echo "Test coverage below 90%. Coverage: $COVERAGE%"
-      #      exit 1
-      #    fi
+            # Check if the corresponding test file exists
+            if [[ ! -f "$TEST_FILE" ]]; then
+              MISSING_TEST_FILES+=("$FILE") # Add to missing test files array if test is not found
+            fi
+          done
+          
+          # Step 3: Report and fail if there are any missing test files
+          if [ ${#MISSING_TEST_FILES[@]} -ne 0 ]; then
+            echo "The following source files do not have corresponding test files:"
+            for MISSING_FILE in "${MISSING_TEST_FILES[@]}"; do
+              echo "$MISSING_FILE"
+            done
+            exit 1 # Fail the workflow
+          else
+            echo "All changed files have corresponding test files."
+            exit 0 # Success
+          fi
